# Site settings
title: Sabbatical 2025
description: Was geschah im Herbst 2025.
url: https://doraeneko.github.io
show_downloads: true
markdown: kramdown
theme: jekyll-theme-cayman
github:
  is_project_page: false
author: A.G.

