title: "Sabbatical 2025"
description: "Was geschah im Herbst 2025."
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

